"""empty message

Revision ID: 150343838be7
Revises: f3854993dec2
Create Date: 2020-08-19 12:11:02.729176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150343838be7'
down_revision = 'f3854993dec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Genre', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Genre', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
