"""empty message

Revision ID: 378aa64982bd
Revises: 346e23618b54
Create Date: 2020-08-31 20:49:06.598303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378aa64982bd'
down_revision = '346e23618b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('genre_artist_genre_id_fkey', 'genre_artist', type_='foreignkey')
    op.drop_constraint('genre_artist_artist_id_fkey', 'genre_artist', type_='foreignkey')
    op.create_foreign_key(None, 'genre_artist', 'Genre', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'genre_artist', 'Artist', ['artist_id'], ['id'])
    op.drop_constraint('genre_venue_genre_id_fkey', 'genre_venue', type_='foreignkey')
    op.drop_constraint('genre_venue_venue_id_fkey', 'genre_venue', type_='foreignkey')
    op.create_foreign_key(None, 'genre_venue', 'Genre', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'genre_venue', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genre_venue', type_='foreignkey')
    op.drop_constraint(None, 'genre_venue', type_='foreignkey')
    op.create_foreign_key('genre_venue_venue_id_fkey', 'genre_venue', 'Venue', ['venue_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('genre_venue_genre_id_fkey', 'genre_venue', 'Genre', ['genre_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'genre_artist', type_='foreignkey')
    op.drop_constraint(None, 'genre_artist', type_='foreignkey')
    op.create_foreign_key('genre_artist_artist_id_fkey', 'genre_artist', 'Artist', ['artist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('genre_artist_genre_id_fkey', 'genre_artist', 'Genre', ['genre_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
