"""empty message

Revision ID: 37a9cb9f2af8
Revises: e0a81ae5ccb0
Create Date: 2020-08-19 12:22:54.434955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a9cb9f2af8'
down_revision = 'e0a81ae5ccb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre_venue', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('genre_venue_artist_id_fkey', 'genre_venue', type_='foreignkey')
    op.create_foreign_key(None, 'genre_venue', 'Venue', ['venue_id'], ['id'])
    op.drop_column('genre_venue', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre_venue', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'genre_venue', type_='foreignkey')
    op.create_foreign_key('genre_venue_artist_id_fkey', 'genre_venue', 'Artist', ['artist_id'], ['id'])
    op.drop_column('genre_venue', 'venue_id')
    # ### end Alembic commands ###
