"""empty message

Revision ID: ac204b616dd9
Revises: 8e1211965a80
Create Date: 2020-09-02 20:00:45.890215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac204b616dd9'
down_revision = '8e1211965a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'duration')
    # ### end Alembic commands ###
