"""empty message

Revision ID: e0a81ae5ccb0
Revises: 150343838be7
Create Date: 2020-08-19 12:16:05.920490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a81ae5ccb0'
down_revision = '150343838be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('genre_artist_genre_id_fkey', 'genre_artist', type_='foreignkey')
    op.create_foreign_key(None, 'genre_artist', 'Genre', ['genre_id'], ['id'])
    op.add_column('genre_venue', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.drop_constraint('genre_venue_venue_id_fkey', 'genre_venue', type_='foreignkey')
    op.create_foreign_key(None, 'genre_venue', 'Genre', ['genre_id'], ['id'])
    op.drop_column('genre_venue', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre_venue', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'genre_venue', type_='foreignkey')
    op.create_foreign_key('genre_venue_venue_id_fkey', 'genre_venue', 'Genre', ['venue_id'], ['id'])
    op.drop_column('genre_venue', 'genre_id')
    op.drop_constraint(None, 'genre_artist', type_='foreignkey')
    op.create_foreign_key('genre_artist_genre_id_fkey', 'genre_artist', 'Venue', ['genre_id'], ['id'])
    # ### end Alembic commands ###
