"""Fixed genre association

Revision ID: f3854993dec2
Revises: d36a5917713b
Create Date: 2020-08-18 23:43:16.217382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3854993dec2'
down_revision = 'd36a5917713b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre_association', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'genre_association', 'Genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genre_association', type_='foreignkey')
    op.drop_column('genre_association', 'genre_id')
    # ### end Alembic commands ###
